### ISSUE TITLE
Undefined variable error after update to 1.0.7

### ISSUE THREAD

**Issue by fazzyx** [kaystrobach/TYPO3.dyncss_scss#13]
Hello,

after update from 1.0.5 to 1.0.7 I get the error "Undefined variable $min: line: 61"
If I revert to version 1.0.5 the error is gone.
Are there breaking changes?

I'm using dyncss with TYPO3 Themes extension and theme_bootstrap4.

TYPO3 version 7.6.11
dyncss version 0.7.9

Greetz Claus

**Comment by fazzyx** [comment]
I found out that the error is caused by custom sass.
I use:
@include media-breakpoint-only(md) {...}
@include media-breakpoint-only(lg) {...}
@include media-breakpoint-only(xl) {...}

If I remove the md and lg one, no error occurs.
I changed my includes with the ones from bootstrap testing files. Same behavior.
And I tried to leave the definition empty, just using this:
@include media-breakpoint-only(md) {}
@include media-breakpoint-only(lg) {}
@include media-breakpoint-only(xl) {}
Same behavior.

This is very strange.

**Comment by fazzyx** [comment]
I'm not sure, but could it related to this issue?
https://github.com/leafo/scssphp/issues/423

Which version of scssphp include dyncss_scss version 1.0.5?

**Comment by kaystrobach** [comment]
see extem -> dyncss settings to get an idea of installed versions

**Comment by fazzyx** [comment]
@kaystrobach Yes it is v0.6.3

**Comment by kaystrobach** [comment]
@tdeuling wants to update the parser this week - so hopefully this solves the problem

**Comment by kaystrobach** [comment]
but you can also try by simpy replacing the parser manually in the extension

**Comment by tdeuling** [comment]
@fazzyx we just merge the current version of leafo scss parser. Please try again and give some feedback if it works now as expected. Thanks.

**Comment by fazzyx** [comment]
@tdeuling Thank you. Looks like it is gone:) I didn't used this setup since the error occur:)
