### ISSUE TITLE
Class 'Leafo\ScssPhp\Compiler' not found

### ISSUE THREAD

**Issue by stillerfritz** [kaystrobach/TYPO3.dyncss_scss#19]
hi there.

On pages with the plugin "aimeos" inserted, I'm receiving an error in frontend view:

Class 'Leafo\ScssPhp\Compiler' not found
Error thrown in dyncss_scss/Classes/Parser/ScssParser.php in line 17

regardless whether I use dyncss_scss 1.1.1 or 1.2

System latest TYPO3 8.7
t3sbootstrap 4.1.1
aimeos 18.1.1

any clue on this is much appreciated.
let me know if you need further details

**Comment by kaystrobach** [comment]
have you tried another version of dyncss? maybe an older one or an reinstall, sounds like an autoloader issue. Are you using composer or classic mode?

**Comment by stillerfritz** [comment]
thanks for your quick reply!
it definetly seems to be an issue with aimeos.
with aimeos installed I can't even open the dyncss settings in the extension manager.
same error
without it works
tried different versions of aimos and dyncss & dyncss_scss - no success
typo3 classic mode in use
although it doesn't seem to be an issue with dyncss_scss do have any further advice of how to deal with it.

cheers

**Comment by kaystrobach** [comment]
hey @stillerfritz ,
as i do not use ameos on any project and this can be a rather complex task I can offer you the following options:

* You sponsor the development (via our open source hours agreement) and send me an request to ks@4viewture.eu
* You provide more information (stacktraces / exceptions / ...) and i may take a look without any promise

Please understand that we offer the best support we can, but that developing / using OpenSource also includes investments.

Have a nice day
Kay

**Comment by stillerfritz** [comment]
I do agree completely. i have described the issue to the aimeos developer. let's see what they come up with.
will keep you posted. 
thanks for your attention and your great work on typo3

be good

**Comment by kaystrobach** [comment]
can you please link the aimeos issue tracker issue here, this might make it possible to find solutions to this problem for future research

**Comment by stillerfritz** [comment]
seems I have to chum up with composer mode:
https://aimeos.org/help/post5811.html
