### ISSUE TITLE
Publish v1.1.2 and v1.2.0 on TER

### ISSUE THREAD

**Issue by yeldiRium** [kaystrobach/TYPO3.dyncss_scss#22]
Are there plans to publish the current version to the TER?
In 1.1.1 `leafo/scssphp` is missing from the requirements and thus the extension does not work without explicitly installing one of its dependencies.

This can be worked around of course, but a new release would be the nicer solution in my opinion.

**Comment by kaystrobach** [comment]
I'm primarly using composer ... but will think about it, will check wether i can reestablish the automated publishing workflow again.

please remind me, if I miss it until the end of the week.

**Comment by yeldiRium** [comment]
Will do and thank you for the quick response :)

**Comment by yeldiRium** [comment]
I forgot to remind you 😂

**Comment by YannikSMYLIE** [comment]
Any news?
